server:
  port: 8900

spring:
  application:
    name: spring-cache

  redis:
    host: localhost
    database: 0
    timeout:
    #    password: 111111
    port: 6379
    jedis:
      pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 2

